-- Create the products table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  subcategory text,
  brand text,
  details text,
  image_url text default '/product-placeholder.svg',
  in_stock boolean default true,
  featured boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.products enable row level security;

-- Create policies to allow public read access
create policy "Enable read access for all users"
  on public.products for select
  using ( true );

-- Create policies to allow insert/update/delete for authenticated users 
-- (or public if you are using the anon key for admin actions without auth for now)
-- For this setup with your simple admin password, we will allow anon writes 
-- but you should implement proper Supabase Auth later.
create policy "Enable write access for all users"
  on public.products for insert
  with check ( true );

create policy "Enable update access for all users"
  on public.products for update
  using ( true );

create policy "Enable delete access for all users"
  on public.products for delete
  using ( true );

-- Create Storage Bucket for Product Images
insert into storage.buckets (id, name, public)
values ('products', 'products', true);

-- Allow public access to storage
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'products' );

create policy "Public Insert"
  on storage.objects for insert
  with check ( bucket_id = 'products' );
